staticSites:
  - name: finalProjectFrontend
    buildCommand: bun install --frozen-lockfile && bun run build
    publishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        sync: false
      - key: VITE_LEGACY_API_BASE_URL
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
